version: '3.8'
services:
  dev-db:
    container_name: dev_db_postgres13
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
    networks:
      - devnetwork
    volumes:
      - psql_data:/var/lib/mysql
    expose:
      - '5432'
  test-db:
    container_name: test_db_postgres13
    # image: docker.uclv.cu/postgres:13
    image: postgres:13
    ports:
      - 5435:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
    networks:
      - testnetwork
volumes:
  psql_data:
networks:
  testnetwork:
  devnetwork:
